;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Fabula.Affinity.Air.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Air.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Air.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Air.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Bolt.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Bolt.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Bolt.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Bolt.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Dark.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Dark.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Dark.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Dark.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Earth.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Earth.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Earth.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Earth.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Fire.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Fire.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Fire.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Fire.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Ice.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Ice.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Ice.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Ice.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Light.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Light.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Light.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Light.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Phys.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Phys.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Phys.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Phys.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Poison.Absorption",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Poison.Immunity",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Poison.Resistance",DevComment="")
+GameplayTagList=(Tag="Fabula.Affinity.Poison.Vulnerability",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Air",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Bolt",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Dark",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Earth",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Fire",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Ice",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Light",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Phys",DevComment="")
+GameplayTagList=(Tag="Fabula.DamageType.Poison",DevComment="")
+GameplayTagList=(Tag="Fabula.SetByCaller.Damage",DevComment="")
+GameplayTagList=(Tag="Fabula.SetByCaller.NumOfTargets",DevComment="")
+GameplayTagList=(Tag="Fabula.Status.Dead",DevComment="")
+GameplayTagList=(Tag="Fabula.Status.Protected.Guard",DevComment="")

